// (c) Copyright Ascensio System SIA 2009-2026
//
// This program is a free software product.
// You can redistribute it and/or modify it under the terms
// of the GNU Affero General Public License (AGPL) version 3 as published by the Free Software
// Foundation. In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended
// to the effect that Ascensio System SIA expressly excludes the warranty of non-infringement of
// any third-party rights.
//
// This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For details, see
// the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
//
// You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.
//
// The  interactive user interfaces in modified source and object code versions of the Program must
// display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
//
// Pursuant to Section 7(b) of the License you must retain the original Product logo when
// distributing the program. Pursuant to Section 7(e) we decline to grant you any rights under
// trademark law for use of our trademarks.
//
// All the Product's GUI elements, including illustrations and icon sets, as well as technical writing
// content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0
// International. See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode

import { defineConfig, type Plugin, transformWithEsbuild } from "vite";
import react from "@vitejs/plugin-react";
import svgr from "vite-plugin-svgr";
import path from "path";
import fs from "fs";
import crypto from "crypto";

const pkg = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, "package.json"), "utf-8"),
);

const fileHash = (filePath: string): string => {
  try {
    const content = fs.readFileSync(filePath);
    return crypto.createHash("md5").update(content).digest("hex");
  } catch {
    return "";
  }
};

const publicScriptsDir = path.resolve(__dirname, "../../public/scripts");

const getBuildDate = () => {
  const today = new Date();
  return `${today.toISOString().split(".")[0]}Z`;
};

const getBuildYear = () => new Date().getFullYear();

const banner = `/*
* (c) Copyright Ascensio System SIA 2009-${getBuildYear()}. All rights reserved
*
* https://www.onlyoffice.com/
*
* Version: ${pkg.version} (build at: ${getBuildDate()})
*/`;

// ---------------------------------------------------------------------------
// Custom plugin: transform JSX in .js files via esbuild.
// The project was ejected from CRA where Babel processed all .js files with
// JSX support. Vite/Rollup only handles JSX in .jsx/.tsx files by default.
// This plugin pre-transforms .js files containing JSX before Rollup parses them.
// ---------------------------------------------------------------------------
const jsxInJsPlugin = (): Plugin => ({
  name: "jsx-in-js",
  enforce: "pre",
  config() {
    return {
      optimizeDeps: {
        esbuildOptions: {
          loader: {
            ".js": "jsx",
          },
        },
      },
    };
  },
  async transform(code, id) {
    if (!id.endsWith(".js") || id.includes("node_modules")) return null;
    // Quick check: skip files that clearly don't contain JSX.
    // Match opening JSX tags (<Component, <div) or closing tags (</),
    // but not plain comparison operators (a < b).
    if (!/(<\/|<[A-Za-z])/.test(code)) return null;

    return transformWithEsbuild(code, id, {
      loader: "jsx",
      jsx: "automatic",
      jsxImportSource: "react",
    });
  },
});

// ---------------------------------------------------------------------------
// Custom plugin: resolve *.json?url imports to public URL path strings.
//
// In Webpack, file-loader with emitFile:false returned a path like
// "locales/ar-SA/AIRoom.json?hash=abc". The autoGeneratedTranslations.js
// file imports ~2900 JSON locale files this way. loadLanguagePath() in
// language-helpers.js then parses that path to build the i18next fetch URL.
//
// This plugin intercepts *.json?url imports, resolves the alias
// (ASSETS_DIR / PUBLIC_DIR), computes the relative path from the
// corresponding public/ directory, and returns it as a default export string.
// ---------------------------------------------------------------------------
const jsonUrlPlugin = (): Plugin => {
  const assetsDir = path.resolve(__dirname, "public");
  const publicDir = path.resolve(__dirname, "../../public");

  return {
    name: "json-url-import",
    enforce: "pre",

    resolveId(id, importer) {
      if (!id.endsWith(".json?url") || !importer) return null;

      // Strip the ?url suffix to resolve the real file path
      const cleanId = id.replace("?url", "");

      // Manually resolve aliases
      let resolved: string;
      if (cleanId.startsWith("ASSETS_DIR/")) {
        resolved = path.resolve(assetsDir, cleanId.slice("ASSETS_DIR/".length));
      } else if (cleanId.startsWith("PUBLIC_DIR/")) {
        resolved = path.resolve(publicDir, cleanId.slice("PUBLIC_DIR/".length));
      } else if (importer) {
        resolved = path.resolve(path.dirname(importer), cleanId);
      } else {
        return null;
      }

      // Return a virtual module ID. Encode the path as base64 to avoid
      // vite:json intercepting IDs that end with .json
      const encoded = Buffer.from(resolved).toString("base64url");
      return `\0json-url:${encoded}`;
    },

    load(id) {
      if (!id.startsWith("\0json-url:")) return null;

      const encoded = id.slice("\0json-url:".length);
      const resolved = Buffer.from(encoded, "base64url").toString();

      // Compute the URL path relative to the public directory
      let relativePath: string;
      if (resolved.startsWith(assetsDir)) {
        relativePath = path.relative(assetsDir, resolved);
      } else if (resolved.startsWith(publicDir)) {
        relativePath = path.relative(publicDir, resolved);
      } else {
        relativePath = path.basename(resolved);
      }

      // Normalize to forward slashes
      const urlPath = "/" + relativePath.split(path.sep).join("/");
      return `export default ${JSON.stringify(urlPath)};`;
    },
  };
};

// ---------------------------------------------------------------------------
// Custom plugin: inject content hashes into index.html placeholders.
// In dev mode, when accessed through a backend proxy (e.g. port 8092),
// rewrite the module entry point to use an absolute Vite URL so the browser
// loads ES modules directly from the Vite dev server instead of the proxy.
// ---------------------------------------------------------------------------
const htmlTransformPlugin = (): Plugin => ({
  name: "html-transform",
  transformIndexHtml: {
    order: "pre",
    handler(html, ctx) {
      html = html
        .replace(
          /%VITE_BROWSER_DETECTOR_HASH%/g,
          fileHash(path.join(publicScriptsDir, "browserDetector.js")),
        )
        .replace(
          /%VITE_CONFIG_HASH%/g,
          fileHash(path.join(publicScriptsDir, "config.json")),
        );

      // In dev mode, use absolute URLs so modules load from Vite, not the proxy
      if (ctx.server) {
        const serverConfig = ctx.server.config.server;
        const host =
          process.env.VITE_DEV_HOST ||
          (typeof serverConfig.host === "string"
            ? serverConfig.host
            : "localhost");
        const port = serverConfig.port || 5001;
        const viteOrigin = `http://${host}:${port}`;
        html = html.replace(
          'src="/src/bootstrap.js"',
          `src="${viteOrigin}/src/bootstrap.js"`,
        );
      }

      return html;
    },
  },
});

// ---------------------------------------------------------------------------
// Custom plugin: add copyright banner to JS/CSS output (production only)
// ---------------------------------------------------------------------------
const bannerPlugin = (): Plugin => ({
  name: "banner-plugin",
  generateBundle(_, bundle) {
    for (const chunk of Object.values(bundle)) {
      if (chunk.type === "chunk") {
        chunk.code = banner + "\n" + chunk.code;
      } else if (
        chunk.type === "asset" &&
        typeof chunk.fileName === "string" &&
        chunk.fileName.endsWith(".css") &&
        typeof chunk.source === "string"
      ) {
        chunk.source = banner + "\n" + chunk.source;
      }
    }
  },
});

// ---------------------------------------------------------------------------
// Custom plugin: copy and minify locale JSON files to dist/ (production build)
// Replaces Webpack's CopyPlugin with minifyJson transform.
// ---------------------------------------------------------------------------
function copyAndMinifyLocales(src: string, dest: string) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyAndMinifyLocales(srcPath, destPath);
    } else if (entry.name.endsWith(".json")) {
      try {
        const content = JSON.parse(fs.readFileSync(srcPath, "utf-8"));
        fs.writeFileSync(destPath, JSON.stringify(content), "utf-8");
      } catch {
        fs.copyFileSync(srcPath, destPath);
      }
    }
  }
}

const copyLocalesPlugin = (): Plugin => ({
  name: "copy-locales",
  closeBundle() {
    const srcDir = path.resolve(__dirname, "public/locales");
    const destDir = path.resolve(__dirname, "dist/locales");
    copyAndMinifyLocales(srcDir, destDir);
  },
});

// ---------------------------------------------------------------------------
// Custom plugin: copy fonts CSS and font files to dist/static/ (production build)
// In production these are served by nginx from /var/www/public/ at /static/.
// For E2E tests (serve dist -s) and self-contained builds, we need them in dist/.
// ---------------------------------------------------------------------------
const copyFontsPlugin = (): Plugin => ({
  name: "copy-fonts",
  closeBundle() {
    const rootPublicDir = path.resolve(__dirname, "../../public");

    // Copy css/fonts.css → dist/static/css/fonts.css
    const cssSrc = path.join(rootPublicDir, "css/fonts.css");
    const cssDest = path.resolve(__dirname, "dist/static/css");
    if (fs.existsSync(cssSrc)) {
      fs.mkdirSync(cssDest, { recursive: true });
      fs.copyFileSync(cssSrc, path.join(cssDest, "fonts.css"));
    }

    // Copy fonts/v35/ → dist/static/fonts/v35/
    const fontsSrc = path.join(rootPublicDir, "fonts");
    const fontsDest = path.resolve(__dirname, "dist/static/fonts");
    if (fs.existsSync(fontsSrc)) {
      const copyDir = (src: string, dest: string) => {
        fs.mkdirSync(dest, { recursive: true });
        for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
          const srcPath = path.join(src, entry.name);
          const destPath = path.join(dest, entry.name);
          if (entry.isDirectory()) {
            copyDir(srcPath, destPath);
          } else {
            fs.copyFileSync(srcPath, destPath);
          }
        }
      };
      copyDir(fontsSrc, fontsDest);
    }
  },
});

// ---------------------------------------------------------------------------
// Custom plugin: serve files from root public/ directory in dev mode.
// The root public/ contains scripts/config.json, images/, css/fonts.css, etc.
// These are normally served by nginx in production, but in dev we need
// Vite to serve them as a fallback.
// ---------------------------------------------------------------------------
const serveRootPublicPlugin = (): Plugin => {
  const rootPublicDir = path.resolve(__dirname, "../../public");

  return {
    name: "serve-root-public",
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (!req.url) return next();

        const urlPath = req.url.split("?")[0];
        const filePath = path.join(rootPublicDir, urlPath);

        if (fs.existsSync(filePath) && fs.statSync(filePath).isFile()) {
          const ext = path.extname(filePath);
          const mimeTypes: Record<string, string> = {
            ".json": "application/json",
            ".js": "application/javascript",
            ".css": "text/css",
            ".svg": "image/svg+xml",
            ".png": "image/png",
            ".jpg": "image/jpeg",
            ".gif": "image/gif",
            ".ico": "image/x-icon",
            ".woff": "font/woff",
            ".woff2": "font/woff2",
            ".ttf": "font/ttf",
            ".eot": "application/vnd.ms-fontobject",
          };
          res.setHeader(
            "Content-Type",
            mimeTypes[ext] || "application/octet-stream",
          );
          fs.createReadStream(filePath).pipe(res);
          return;
        }

        next();
      });
    },
  };
};

// ===========================================================================
// Main Vite configuration
// ===========================================================================
export default defineConfig(({ mode }) => {
  const isProduction = mode === "production";

  return {
    root: __dirname,
    base: "/",

    resolve: {
      alias: {
        PUBLIC_DIR: path.resolve(__dirname, "../../public"),
        ASSETS_DIR: path.resolve(__dirname, "./public"),
        SRC_DIR: path.resolve(__dirname, "./src"),
        PACKAGE_FILE: path.resolve(__dirname, "package.json"),
        COMMON_DIR: path.resolve(__dirname, "../common"),
        "@docspace/shared": path.resolve(__dirname, "../shared"),
        "@docspace/ui-kit": path.resolve(__dirname, "../../libs/ui-kit"),
      },
      extensions: [".tsx", ".ts", ".jsx", ".js", ".json"],
      dedupe: ["styled-components", "react", "react-dom"],
    },

    define: {
      VERSION: JSON.stringify(pkg.version),
      BUILD_AT: JSON.stringify(getBuildDate()),
    },

    plugins: [
      jsxInJsPlugin(),
      jsonUrlPlugin(),
      svgr({
        svgrOptions: {
          exportType: "default",
          svgo: true,
          svgoConfig: {
            plugins: [
              {
                name: "preset-default",
                params: {
                  overrides: {
                    removeViewBox: false,
                    cleanupIds: false,
                  },
                },
              },
            ],
          },
        },
        include: "**/*.svg",
        exclude: "**/*.svg?url",
      }),
      react(),
      htmlTransformPlugin(),
      serveRootPublicPlugin(),
      isProduction && bannerPlugin(),
      isProduction && copyLocalesPlugin(),
      isProduction && copyFontsPlugin(),
    ].filter(Boolean),

    css: {
      modules: {
        generateScopedName: "[name]__[local]--[hash:base64:5]",
      },
      preprocessorOptions: {
        scss: {
          api: "modern-compiler",
          importers: [
            {
              findFileUrl(url: string) {
                if (url.startsWith("@docspace/ui-kit")) {
                  const resolved = url.replace(
                    "@docspace/ui-kit",
                    path.resolve(__dirname, "../../libs/ui-kit"),
                  );
                  return new URL(`file://${resolved}`);
                }
                if (url.startsWith("@docspace/shared")) {
                  const resolved = url.replace(
                    "@docspace/shared",
                    path.resolve(__dirname, "../shared"),
                  );
                  return new URL(`file://${resolved}`);
                }
                return null;
              },
            },
          ],
        },
      },
    },

    server: {
      port: parseInt(process.env.PORT || "5001"),
      strictPort: true,
      cors: true,
      // Allow the page loaded from the backend proxy (e.g. :8092) to connect
      // to Vite's WebSocket for HMR
      hmr: {
        host: "localhost",
        port: parseInt(process.env.PORT || "5001"),
        protocol: "ws",
      },
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods":
          "GET, POST, PUT, DELETE, PATCH, OPTIONS",
        "Access-Control-Allow-Headers":
          "X-Requested-With, content-type, Authorization",
      },
      fs: {
        allow: [
          path.resolve(__dirname, "../../public"),
          path.resolve(__dirname, "../shared"),
          path.resolve(__dirname, "../../libs"),
          path.resolve(__dirname),
        ],
      },
    },

    build: {
      outDir: "dist",
      sourcemap: isProduction ? "hidden" : "inline",
      rollupOptions: {
        onwarn(warning, warn) {
          // react-virtualized ships a Flow directive that Rollup doesn't understand
          if (warning.code === "MODULE_LEVEL_DIRECTIVE") return;
          // sjcl optionally imports Node "crypto" for PRNG seeding;
          // it falls back to window.crypto in the browser.
          if (warning.message?.includes("externalized for browser")) return;
          // json2-mod uses eval() internally — safe, informational only
          if (
            warning.code === "EVAL" &&
            warning.id?.includes("json2-mod")
          )
            return;
          // Suppress Vite reporter warnings about modules that are both dynamically
          // and statically imported (route-level lazy loading + parent static import).
          // These are informational — they just mean those chunks won't be code-split.
          if (
            warning.message?.includes(
              "dynamic import will not move module into another chunk",
            )
          )
            return;
          warn(warning);
        },
        output: {
          entryFileNames: "static/js/[name].[hash].bundle.js",
          chunkFileNames: "static/js/[name].[hash].js",
          assetFileNames: (assetInfo) => {
            const name = assetInfo.names?.[0] || "";
            if (name.endsWith(".css")) {
              return "static/styles/[name].[hash][extname]";
            }
            return "static/[name].[hash][extname]";
          },
          manualChunks(id) {
            if (id.includes("node_modules")) {
              if (id.includes("firebase")) return "vendor-firebase";
              if (id.includes("mobx")) return "vendor-mobx";
              if (
                id.includes("react-dom") ||
                id.includes("react-router") ||
                id.includes("react-i18next") ||
                id.includes("scheduler")
              )
                return "vendor-react";
              if (id.includes("styled-components")) return "vendor-styled";
              if (id.includes("lodash")) return "vendor-lodash";
            }
          },
        },
      },
      chunkSizeWarningLimit: 1000,
      minify: isProduction ? "esbuild" : false,
      commonjsOptions: {
        // Handle firebase compat and other packages that use require() in ESM
        transformMixedEsModules: true,
      },
    },

    optimizeDeps: {
      include: [
        "react",
        "react-dom",
        "react-router",
        "mobx",
        "mobx-react",
        "styled-components",
        "i18next",
        "react-i18next",
        "axios",
        "lodash",
        "firebase/compat/app",
        "firebase/compat/remote-config",
        "firebase/compat/storage",
        "firebase/compat/database",
      ],
    },
  };
});
